package View;


import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RIVER
 */
public class ECAMMainFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form JTableTest
     */
    public ECAMMainFrame() {
        initComponents();
        ImageIcon img = new ImageIcon("FinalLogo2.jpg");
        this.setIconImage(img.getImage());
        this.setTitle("Data Manager");
        this.setResizable(false);
        deptsComboBox.addItem("Sales");
        deptsComboBox.addItem("Manufacturing");
        deptsComboBox.addItem("Human Resources");
        deptsComboBox.addItem("Engineering");
        deptsComboBox.setSelectedIndex(-1);
        reportDataTable.getTableHeader().setResizingAllowed(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        deptsLabel = new javax.swing.JLabel();
        deptsComboBox = new javax.swing.JComboBox<>();
        reportLabel = new javax.swing.JLabel();
        reportComboBox = new javax.swing.JComboBox<>();
        goButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        scrollbar = new javax.swing.JScrollPane();
        reportDataTable = new javax.swing.JTable();
        menubar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        insertItem = new javax.swing.JMenuItem();
        deleteItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(192, 197, 193));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 70));

        deptsLabel.setForeground(new java.awt.Color(3, 37, 78));
        deptsLabel.setText("Department:");

        deptsComboBox.setBackground(new java.awt.Color(240, 240, 240));
        deptsComboBox.setForeground(new java.awt.Color(3, 37, 78));
        deptsComboBox.setFocusable(false);

        reportLabel.setForeground(new java.awt.Color(3, 37, 78));
        reportLabel.setText("Report:");

        reportComboBox.setBackground(new java.awt.Color(240, 240, 240));
        reportComboBox.setForeground(new java.awt.Color(3, 37, 78));
        reportComboBox.setFocusable(false);
        reportComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportComboBoxActionPerformed(evt);
            }
        });

        goButton.setBackground(new java.awt.Color(3, 37, 78));
        goButton.setForeground(new java.awt.Color(240, 240, 240));
        goButton.setText("Go");
        goButton.setFocusable(false);
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(deptsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deptsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(reportLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(goButton)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportLabel)
                    .addComponent(reportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton)
                    .addComponent(deptsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(192, 197, 193));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollbar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Data:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(3, 37, 78))); // NOI18N
        scrollbar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollbar.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        reportDataTable.setForeground(new java.awt.Color(3, 37, 78));
        reportDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reportDataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        reportDataTable.setRowHeight(50);
        reportDataTable.getTableHeader().setReorderingAllowed(false);
        scrollbar.setViewportView(reportDataTable);

        jPanel4.add(scrollbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 810, 570));

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        fileMenu.setForeground(new java.awt.Color(3, 37, 78));
        fileMenu.setText("File");
        fileMenu.setFocusable(false);

        saveItem.setText("Save Report As...");
        fileMenu.add(saveItem);

        exitItem.setText("Exit");
        fileMenu.add(exitItem);

        menubar.add(fileMenu);

        editMenu.setForeground(new java.awt.Color(3, 37, 78));
        editMenu.setText("Edit");
        editMenu.setFocusable(false);

        insertItem.setText("Insert Row");
        editMenu.add(insertItem);

        deleteItem.setText("Delete Row");
        deleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteItem);

        menubar.add(editMenu);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed

    }//GEN-LAST:event_goButtonActionPerformed

    private void reportComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportComboBoxActionPerformed

    private void deleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem deleteItem;
    private javax.swing.JComboBox<String> deptsComboBox;
    private javax.swing.JLabel deptsLabel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton goButton;
    private javax.swing.JMenuItem insertItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JComboBox<String> reportComboBox;
    private javax.swing.JTable reportDataTable;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JScrollPane scrollbar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the deleteItem
     */
    public javax.swing.JMenuItem getDeleteItem() {
        return deleteItem;
    }

    /**
     * @return the deptsComboBox
     */
    public javax.swing.JComboBox<String> getDeptsComboBox() {
        return deptsComboBox;
    }

    /**
     * @return the exitItem
     */
    public javax.swing.JMenuItem getExitItem() {
        return exitItem;
    }

    /**
     * @return the goButton
     */
    public javax.swing.JButton getGoButton() {
        return goButton;
    }

    /**
     * @return the insertItem
     */
    public javax.swing.JMenuItem getInsertItem() {
        return insertItem;
    }

    /**
     * @return the reportComboBox
     */
    public javax.swing.JComboBox<String> getReportComboBox() {
        return reportComboBox;
    }

    /**
     * @return the reportDataTable
     */
    public javax.swing.JTable getReportDataTable() {
        return reportDataTable;
    }

    /**
     * @return the saveItem
     */
    public javax.swing.JMenuItem getSaveItem() {
        return saveItem;
    }

    /**
     * @return the scrollbar
     */
    public javax.swing.JScrollPane getScrollbar() {
        return scrollbar;
    }
}
